// RobotBuilder Version: 2.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


package org.usfirst.frc4415.SteamShipBot1Final;

// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=IMPORTS
import com.ctre.CANTalon;
import edu.wpi.first.wpilibj.AnalogInput;
import edu.wpi.first.wpilibj.CounterBase.EncodingType;
import edu.wpi.first.wpilibj.DigitalInput;
import edu.wpi.first.wpilibj.DigitalOutput;
import edu.wpi.first.wpilibj.DoubleSolenoid;
import edu.wpi.first.wpilibj.Encoder;
import edu.wpi.first.wpilibj.PIDSourceType;
import edu.wpi.first.wpilibj.RobotDrive;
import edu.wpi.first.wpilibj.Servo;

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=IMPORTS
import edu.wpi.first.wpilibj.livewindow.LiveWindow;

import com.ctre.CANTalon.FeedbackDevice;
import com.ctre.CANTalon.StatusFrameRate;
import com.ctre.CANTalon.TalonControlMode;

/**
 * The RobotMap is a mapping from the ports sensors and actuators are wired into
 * to a variable name. This provides flexibility changing wiring, makes checking
 * the wiring easier and significantly reduces the number of magic numbers
 * floating around.
 */
public class RobotMap {
    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
    public static CANTalon driveTrainfrontLeft;
    public static CANTalon driveTrainfrontRight;
    public static CANTalon driveTrainrearLeft;
    public static CANTalon driveTrainrearRight;
    public static RobotDrive driveTrainRobotDrive4;
    public static DoubleSolenoid driveTrainchangeSolenoid;
    public static Encoder driveTrainQuadratureEncoder1;
    public static AnalogInput driveTrainAnalogInput1;
    public static CANTalon shootershooterMotor;
    public static CANTalon blenderblenderMotor;
    public static CANTalon climberclimberMotor;
    public static Encoder climberQuadratureEncoder1;
    public static CANTalon turretturretMotor;
    public static DigitalInput turretLeftLimit;
    public static DigitalInput turretMiddleLimit;
    public static DigitalInput turretRightLimit;
    public static DoubleSolenoid gearHandlergearHandlerSolenoid;
    public static DoubleSolenoid gearHandlergearGrabSolenoid;
    public static Servo cameraSystemServo1;
    public static Servo cameraSystemServo2;
    public static DigitalOutput cameraSystemLED;
    public static DigitalOutput cameraSystemPin1;
    public static DigitalOutput cameraSystemPin2;
    public static DigitalOutput cameraSystemPin3;
    public static DigitalOutput cameraSystemPin4;
    public static DoubleSolenoid fuelTankDoubleSolenoid;

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS

    public static void init() {
        // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTORS
        driveTrainfrontLeft = new CANTalon(2);
        LiveWindow.addActuator("Drive Train", "frontLeft", driveTrainfrontLeft);
        
        driveTrainfrontRight = new CANTalon(6);
        LiveWindow.addActuator("Drive Train", "frontRight", driveTrainfrontRight);
        
        driveTrainrearLeft = new CANTalon(1);
        LiveWindow.addActuator("Drive Train", "rearLeft", driveTrainrearLeft);
        
        driveTrainrearRight = new CANTalon(5);
        LiveWindow.addActuator("Drive Train", "rearRight", driveTrainrearRight);
        
        driveTrainRobotDrive4 = new RobotDrive(driveTrainfrontLeft, driveTrainrearLeft,
              driveTrainfrontRight, driveTrainrearRight);
        
        driveTrainRobotDrive4.setSafetyEnabled(true);
        driveTrainRobotDrive4.setExpiration(0.1);
        driveTrainRobotDrive4.setSensitivity(0.5);
        driveTrainRobotDrive4.setMaxOutput(1.0);

        driveTrainchangeSolenoid = new DoubleSolenoid(0, 1, 0);
        LiveWindow.addActuator("Drive Train", "changeSolenoid", driveTrainchangeSolenoid);
        
        driveTrainQuadratureEncoder1 = new Encoder(6, 7, false, EncodingType.k4X);
        LiveWindow.addSensor("Drive Train", "Quadrature Encoder 1", driveTrainQuadratureEncoder1);
        driveTrainQuadratureEncoder1.setDistancePerPulse(1.0);
        driveTrainQuadratureEncoder1.setPIDSourceType(PIDSourceType.kDisplacement);
        driveTrainAnalogInput1 = new AnalogInput(0);
        LiveWindow.addSensor("Drive Train", "Analog Input 1", driveTrainAnalogInput1);
        
        shootershooterMotor = new CANTalon(0);
        LiveWindow.addActuator("Shooter", "shooterMotor", shootershooterMotor);
        
        blenderblenderMotor = new CANTalon(3);
        LiveWindow.addActuator("Blender", "blenderMotor", blenderblenderMotor);
        
        climberclimberMotor = new CANTalon(8);
        LiveWindow.addActuator("Climber", "climberMotor", climberclimberMotor);
        
        climberQuadratureEncoder1 = new Encoder(4, 5, false, EncodingType.k4X);
        LiveWindow.addSensor("Climber", "Quadrature Encoder 1", climberQuadratureEncoder1);
        climberQuadratureEncoder1.setDistancePerPulse(1.0);
        climberQuadratureEncoder1.setPIDSourceType(PIDSourceType.kDisplacement);
        turretturretMotor = new CANTalon(4);
        LiveWindow.addActuator("Turret", "turretMotor", turretturretMotor);
        
        turretLeftLimit = new DigitalInput(2);
        LiveWindow.addSensor("Turret", "Left Limit", turretLeftLimit);
        
        turretMiddleLimit = new DigitalInput(0);
        LiveWindow.addSensor("Turret", "Middle Limit", turretMiddleLimit);
        
        turretRightLimit = new DigitalInput(1);
        LiveWindow.addSensor("Turret", "Right Limit", turretRightLimit);
        
        gearHandlergearHandlerSolenoid = new DoubleSolenoid(0, 4, 5);
        LiveWindow.addActuator("Gear Handler", "gearHandlerSolenoid", gearHandlergearHandlerSolenoid);
        
        gearHandlergearGrabSolenoid = new DoubleSolenoid(0, 3, 2);
        LiveWindow.addActuator("Gear Handler", "gearGrabSolenoid", gearHandlergearGrabSolenoid);
        
        cameraSystemServo1 = new Servo(0);
        LiveWindow.addActuator("Camera System", "Servo 1", cameraSystemServo1);
        
        cameraSystemServo2 = new Servo(1);
        LiveWindow.addActuator("Camera System", "Servo 2", cameraSystemServo2);
        
        cameraSystemLED = new DigitalOutput(8);
        LiveWindow.addActuator("Camera System", "LED", cameraSystemLED);
        
        cameraSystemPin1 = new DigitalOutput(3);
        LiveWindow.addActuator("Camera System", "Pin 1", cameraSystemPin1);
        
        cameraSystemPin2 = new DigitalOutput(9);
        LiveWindow.addActuator("Camera System", "Pin 2", cameraSystemPin2);
        
        cameraSystemPin3 = new DigitalOutput(10);
        LiveWindow.addActuator("Camera System", "Pin 3", cameraSystemPin3);
        
        cameraSystemPin4 = new DigitalOutput(11);
        LiveWindow.addActuator("Camera System", "Pin 4", cameraSystemPin4);
        
        fuelTankDoubleSolenoid = new DoubleSolenoid(0, 6, 7);
        LiveWindow.addActuator("Fuel Tank", "Double Solenoid", fuelTankDoubleSolenoid);
        

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTORS
        shootershooterMotor.setInverted(true);
        shootershooterMotor.setStatusFrameRateMs(StatusFrameRate.Feedback, 1);
        shootershooterMotor.changeControlMode(TalonControlMode.Speed);
        shootershooterMotor.setFeedbackDevice(FeedbackDevice.QuadEncoder);
        shootershooterMotor.reverseSensor(true);
		shootershooterMotor.configEncoderCodesPerRev(1024);
		shootershooterMotor.configNominalOutputVoltage(+0.0f, +0.0f);
		shootershooterMotor.configPeakOutputVoltage(+12.0f, -12.0f);
		shootershooterMotor.setProfile(0);
		shootershooterMotor.setF(.12);
		shootershooterMotor.setP(.3);
		shootershooterMotor.setI(0.00005);
		shootershooterMotor.setD(1);
        turretturretMotor.setInverted(true);
        
    }
    
}
