// RobotBuilder Version: 2.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


package org.usfirst.frc4415.SteamShipBot1Final.commands;
import edu.wpi.first.wpilibj.command.Command;
import edu.wpi.first.wpilibj.smartdashboard.SmartDashboard;

import org.usfirst.frc4415.SteamShipBot1Final.Robot;

public class ShooterDefault extends Command {

    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=VARIABLE_DECLARATIONS
 
    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=VARIABLE_DECLARATIONS

    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTOR
    public ShooterDefault() {

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTOR
        // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=VARIABLE_SETTING

        // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=VARIABLE_SETTING
        // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=REQUIRES
        requires(Robot.shooter);

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=REQUIRES
    }
    
    // Called just before this Command runs the first time
    protected void initialize() {
 //   	Robot.shooter.set(steadyStateSetPoint);

    }

    // Called repeatedly when this Command is scheduled to run
    protected void execute() {
    	double joystick = Robot.oi.getShooterJoystick().getRawAxis(1) * -1;
    	
    	if (joystick > .25) {
    		Robot.shooter.setpointUp();
    	} else if (joystick < -.25) {
    		Robot.shooter.setpointDown();
    	}
    	
    	// added code that might not need to be used on the other robot
    	
    	if (Robot.shooter.getSetpoint() >= 1200) {
    		Robot.shooter.setSetpoint(1200);
    	} else {
    		Robot.shooter.setSetpoint(Robot.shooter.getSetpoint());
    	}
    	
    	if (Robot.shooter.getSetpoint() <= 500) {
    		Robot.shooter.setSetpoint(500);
    	} else {
    		Robot.shooter.setSetpoint(Robot.shooter.getSetpoint());
    	}
    }

    // Make this return true when this Command no longer needs to run execute()
    protected boolean isFinished() {
        return false;
    }

    // Called once after isFinished returns true
    protected void end() {
    	Robot.shooter.stopMotor();
    }

    // Called when another command which requires one or more of the same
    // subsystems is scheduled to run
    protected void interrupted() {
    }
}
