// RobotBuilder Version: 2.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


package org.usfirst.frc4415.SteamShipBot1Final.subsystems;

import org.usfirst.frc4415.SteamShipBot1Final.RobotMap;
import org.usfirst.frc4415.SteamShipBot1Final.commands.*;
import edu.wpi.first.wpilibj.DigitalOutput;

import edu.wpi.first.wpilibj.command.Subsystem;


/**
 *
 */
public class LEDPins extends Subsystem {

    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTANTS

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTANTS

    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
    private final DigitalOutput digitalOutput6 = RobotMap.lEDPinsDigitalOutput6;
    private final DigitalOutput digitalOutput7 = RobotMap.lEDPinsDigitalOutput7;
    private final DigitalOutput digitalOutput8 = RobotMap.lEDPinsDigitalOutput8;
    private final DigitalOutput digitalOutput9 = RobotMap.lEDPinsDigitalOutput9;

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS


    // Put methods for controlling this subsystem
    // here. Call these from Commands.

    public void initDefaultCommand() {
        // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DEFAULT_COMMAND


    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DEFAULT_COMMAND

        // Set the default command for a subsystem here.
        // setDefaultCommand(new MySpecialCommand());
    }
    
    public void setPin6Low() {
    	digitalOutput6.set(false);
    }
    
    public void setPin6High() {
    	digitalOutput6.set(true);
    }
    
    public void setPin7Low() {
    	digitalOutput7.set(false);
    }
    
    public void setPin7High() {
    	digitalOutput7.set(true);
    }
    
    public void setPin8Low() {
    	digitalOutput8.set(false);
    }
    
    public void setPin8High() {
    	digitalOutput8.set(true);
    }
    
    public void setPin9Low() {
    	digitalOutput9.set(false);
    }
    
    public void setPin3High() {
    	digitalOutput9.set(true);
    }
    
    /*public boolean getPin6() {
    	return digitalOutput6.get();
    }
    
    public boolean getPin7() {
    	return digitalOutput7.get();
    }
    
    public boolean getPin8() {
    	return digitalOutput8.get();
    }
    
    public boolean getPin9() {
    	return digitalOutput9.get();
    }*/
    
    // Standard Direction
    public void program1() {
    	digitalOutput6.set(false);
    	digitalOutput7.set(false);
    	digitalOutput8.set(false);
    	digitalOutput6.set(true);
    }
    
    // 2nd Standard Direction
    public void program2() {
    	digitalOutput6.set(false);
    	digitalOutput7.set(false);
    	digitalOutput8.set(true);
    	digitalOutput6.set(false);
    }
    
    // Standard Gyro On
    public void program3() {
    	digitalOutput6.set(false);
    	digitalOutput7.set(false);
    	digitalOutput8.set(true);
    	digitalOutput6.set(true);
    }
    
    // Standard Gyro Off
    public void program4() {
    	digitalOutput6.set(false);
    	digitalOutput7.set(true);
    	digitalOutput8.set(false);
    	digitalOutput6.set(true);
    }
    
    // Standard Mecanum
    public void program5() {
    	digitalOutput6.set(false);
    	digitalOutput7.set(true);
    	digitalOutput8.set(false);
    	digitalOutput6.set(true);
    }
    
    // Standard Arcade
    public void program6() {
    	digitalOutput6.set(false);
    	digitalOutput7.set(true);
    	digitalOutput8.set(true);
    	digitalOutput6.set(false);
    }
    
}

