// RobotBuilder Version: 2.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


package org.usfirst.frc4415.SteamShipBot1Final.subsystems;

import org.usfirst.frc4415.SteamShipBot1Final.RobotMap;
import org.usfirst.frc4415.SteamShipBot1Final.commands.*;
import edu.wpi.first.wpilibj.DigitalOutput;

import edu.wpi.first.wpilibj.command.Subsystem;


/**
 *
 */
public class LEDPins extends Subsystem {

    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTANTS

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTANTS

    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
    private final DigitalOutput digitalOutput1 = RobotMap.lEDPinsDigitalOutput1;
    private final DigitalOutput digitalOutput2 = RobotMap.lEDPinsDigitalOutput2;
    private final DigitalOutput digitalOutput3 = RobotMap.lEDPinsDigitalOutput3;
    private final DigitalOutput digitalOutput4 = RobotMap.lEDPinsDigitalOutput4;

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS


    // Put methods for controlling this subsystem
    // here. Call these from Commands.

    public void initDefaultCommand() {
        // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DEFAULT_COMMAND


    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DEFAULT_COMMAND

        // Set the default command for a subsystem here.
        // setDefaultCommand(new MySpecialCommand());
    }
    
    public void setPin1Low() {
    	digitalOutput1.set(false);
    }
    
    public void setPin1High() {
    	digitalOutput1.set(true);
    }
    
    public void setPin2Low() {
    	digitalOutput2.set(false);
    }
    
    public void setPin2High() {
    	digitalOutput2.set(true);
    }
    
    public void setPin3Low() {
    	digitalOutput3.set(false);
    }
    
    public void setPin3High() {
    	digitalOutput3.set(true);
    }
    
    public void setPin4Low() {
    	digitalOutput4.set(false);
    }
    
    public void setPin4High() {
    	digitalOutput4.set(true);
    }
    
    public boolean getPin1() {
    	return digitalOutput1.get();
    }
    
    public boolean getPin2() {
    	return digitalOutput2.get();
    }
    
    public boolean getPin3() {
    	return digitalOutput3.get();
    }
    
    public boolean getPin4() {
    	return digitalOutput4.get();
    }
    
    // Standard Direction
    public void program1() {
    	digitalOutput1.set(false);
    	digitalOutput2.set(false);
    	digitalOutput3.set(false);
    	digitalOutput4.set(true);
    }
    
    // 2nd Standard Direction
    public void program2() {
    	digitalOutput1.set(false);
    	digitalOutput2.set(false);
    	digitalOutput3.set(true);
    	digitalOutput4.set(false);
    }
    
    // Standard Gyro On
    public void program3() {
    	digitalOutput1.set(false);
    	digitalOutput2.set(false);
    	digitalOutput3.set(true);
    	digitalOutput4.set(true);
    }
    
    // Standard Gyro Off
    public void program4() {
    	digitalOutput1.set(false);
    	digitalOutput2.set(true);
    	digitalOutput3.set(false);
    	digitalOutput4.set(true);
    }
    
    // Standard Mecanum
    public void program5() {
    	digitalOutput1.set(false);
    	digitalOutput2.set(true);
    	digitalOutput3.set(false);
    	digitalOutput4.set(true);
    }
    
    // Standard Arcade
    public void program6() {
    	digitalOutput1.set(false);
    	digitalOutput2.set(true);
    	digitalOutput3.set(true);
    	digitalOutput4.set(false);
    }
    
}

